### PR TITLE
Feature: Add BlueMush as a contributor(Manually)

### LINKED ISSUE #9: Task: Add BlueMush to the list of contributors on the README.md
# Task Title

Task: Add BlueMush to the list of contributors on the README.md

## Task Description

This Task will add BlueMush to the list of contributors on the README.md

### PR DESCRIPTION
**Pull request by laggingmel**
# Story Title

Task: Add BlueMush to the list of contributors on the README.md

## Changes made

Update the table

## How does the solution address the problem

This PR will add BlueMush as contributor

## Linked issues

Resolves #9

### CODE REVIEW

**Comment by BosEriko** [comment]
Can you kindly update the link on the README.md contributors?

As you can see it's using this link:
https://github.com/kuru-project/main-website-client

It's the wrong link. Can you fix both the entry? The one that you added and the one with mine?

Thanks!

**Comment by laggingmel** [comment]
My bad, I'll fix it right away

**Comment by BosEriko** [comment]
> My bad, I'll fix it right away

Never did say it was your fault, though. It was mine.

**Comment by laggingmel** [comment]
I'll replace it with our github page? like this link: https://github.com/rpasamonte97 and this https://github.com/BosEriko?

**Comment by BosEriko** [comment]
> I'll replace it with our github page? like this link: https://github.com/rpasamonte97 and this https://github.com/BosEriko?

no. can you try to understand what the link is for? no guessing this time.

**Comment by BosEriko** [comment]
Please fix conflicts @rpasamonte97. Thank you!

**Pull request closed without merging**
